### ISSUE TITLE
Tagging/Statuses

### ISSUE THREAD

**Issue by gn0rt0n** [plank/laravel-checkpoint#4]
From reviewing the documentation and quickly reviewing the code I can't tell if this allows publishing based on tags.

**Use Case:**
1. Create Model
2. Tag Model as "Draft" - Not visible via scope
3. Tag Model as "Published" - Now visible (call it V1)
4. Update Model (V1) - Saved as new checkpoint (v2) Tag as "Draft"
5. V1 should still be visible. - Status  Published
6. V2 should not be visible - Status Draft
7. Tag V2 Model as "Published"
8. V1 is no longer visible as the date stamp is older than V2, but is still accessible if looking for point-in-time
9. V2 is now visible by default

Does this make sense, and is this possible with this package?

**Comment by m-triassi** [comment]
@gn0rt0n This is indeed possible. Though you wouldn't create checkpoints for draft state, but rather filter draft state models away via global scopes. 

For example imagine you have model `Foo` which uses the trait `HasRevisions`, and a custom scope query `scopePublished()`. If you extend the `Checkpoint` model and override the base scope queries `scopeOlderThan()` and `scopeNewerThan()` to look like the following: 

```
public function scopeOlderThan(Builder $query, $moment, $strict = true)
    {
        return parent::scopeOlderThan($query, $moment, $strict)->published();
    }
```
Then when browsing by Checkpoints, you would automatically filter unpublished instances of `Foo`. The package automatically uses these scope queries in the global scopes it applies to queries. Just make sure to set the new `Checkpoint` model via the package's config file.

The package aims to gather many revisions under a single "Tag", as you put it, so that your application state is browsable at different points in time. 

Please let me know if that answers your question :)

**Comment by gn0rt0n** [comment]
@m-triassi thank you for the explanation. It makes sense and I have an idea how I want to implement this in a test project. I love the work on this so far. Keep it up!

**Comment by m-triassi** [comment]
Thanks so much for the kind words and good luck on your project! 

Closing as question is answered
